version: "3"
services:
    pryv_api:
        build: 
          context: .
          dockerfile: Dockerfile
        image: pryv_api:1.0.0
        container_name: "pryv_api"
        restart: "always"
        links:
            - pryv_mongo
        depends_on:
            - pryv_mongo
        #only for local development volumes:
        #    - .:/app
        networks:
          - app-network
    pryv_mail:
        image: pryv_api:1.0.0
        command: "yarn mail"
        container_name: "pryv_mail"
        restart: "always"
        depends_on:
            - pryv_api
        volumes:
          - ./var-pryv/logs/:/app/var-pryv/logs/
          #only for local development - .:/app
        networks:
          - app-network    
    pryv_mongo:
        image: mongo:3.6.18
        container_name: "pryv_mongo"
        restart: "no"
        environment:
            MONGO_INITDB_ROOT_USERNAME: api-server
            MONGO_INITDB_ROOT_PASSWORD: OVERRIDEME
            MONGO_INITDB_DATABASE: pryv-node
        volumes:
            - ./var-pryv/mongodb/conf/:/app/conf/:ro
            - ./var-pryv/mongodb/data/:/app/data/
            - ./var-pryv/mongodb/log/:/app/log/
            - ./var-pryv/mongodb/backup/:/app/backup/
        networks:
          - app-network
          
    pryv_nginx:
        build: 
          context: .
          dockerfile: Dockerfile.nginx
        container_name: "pryv_nginx"
        volumes:
          - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./configs/site.conf:/etc/nginx/site.conf
        ports:
          - 80:80
          - 443:443
        links:
          - pryv_api
          - pryv_mail
        depends_on:
          - pryv_api
          - pryv_mail
        networks:
          - app-network
        environment:
          - NGINX_HOST=my-computer.rec.la
        command: [nginx-debug, '-g', 'daemon off;']

networks:
  app-network:
    driver: bridge    
